### ISSUE TITLE
Disable game input when menu is open.

### ISSUE THREAD

**Issue by matty45** [matty45/Drinol#28]

**Comment by TempAccountNull** [comment]
> _No description provided._

This has to do with the current `WndProc` and MouseInput not returning if the menu is opened. I'll help you with it when I have some time.

**Comment by matty45** [comment]
@all-contributors please add @TempAccountNull for code

**Comment by matty45** [comment]
@all-contributors please add @TempAccountNull for code

**Comment by matty45** [comment]
Does not work in-game, can still look around and left click, right click still get passed to the game
